<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.1;net9.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Version>1.2.0</Version>
        <PackageId>Natify</PackageId>
        <Authors>Natify</Authors>
        <Description>Micro-batching library for NATS messaging with deduplication, TTL-based dedup wheel, reliable ACK/Retry, and zero-copy serialization.</Description>
        <PackageTags>nats;batching;messaging;pubsub</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.34.1"/>
        <PackageReference Include="Grpc.Tools" Version="2.80.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Gcoder.Collections" Version="1.3.0"/>
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.6"/>
        <PackageReference Include="NATS.Net" Version="2.7.3"/>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\*.proto" GrpcServices="None"/>
    </ItemGroup>

</Project>
